### ISSUE TITLE
Error & Is this project still being maintained?

### ISSUE THREAD

**Issue by rimijoker** [essembeh/gnome-extensions-cli#1]
I was trying to use this and ran into the following error
```python
Traceback (most recent call last):
  File "/home/rimijoker/miniconda3/envs/main/bin/gnome-extensions-cli", line 5, in <module>
    from gnome_extensions_cli.cli import main
  File "/home/rimijoker/miniconda3/envs/main/lib/python3.6/site-packages/gnome_extensions_cli/cli.py", line 6, in <module>
    from gnome_extensions_cli.manager import (
  File "/home/rimijoker/miniconda3/envs/main/lib/python3.6/site-packages/gnome_extensions_cli/manager.py", line 17, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'
```
Also is this project still being maintained?

**Comment by essembeh** [comment]
Hi

I still maintain this project, an I still use it very often to keep my gnome extensions up-to-date ;)

It looks like it cannot find the gi library on your system, this library is used to communicate with Gnome to deal with extensions.
This package should be installed on your system, it is a dependency for a large number of gnome packages, like "gnome-tweak-tool", and this same library is used by the Firefox/Chrome extention that install extensions from https://extensions.gnome.org/

Can you check you have it installed? with
```sh
$ apt policy python3-gi
python3-gi:
  Installé : 3.30.4-1
  Candidat : 3.30.4-1
```
But my guess is the you are trying to run *gnome-extensions-cli* from a virtualenv (using miniconda) that does not enable site packages.
When you create a virtual env you can choose to use (or not) all the libraries already installed on your system.
Try adding `--system-site-packages` to yhe command you use to create your virtualenv.

I hope this will fix your problem, if it does not, please give me more details, like your distribution...

**Comment by rimijoker** [comment]
It worked 🎉
I deactivated my conda env and it works now.
Thank you for creating this project, also consider creating some issues for new features, I would love to contribute. 🙂

**Comment by essembeh** [comment]
I'm glad it solved your problem.
To be honest I don't really understand why Gnome3 itself does not embed a command line tool to manage its extensions, after years and many versions of Gnome3.

There are some other command line tools to do it, but as far as I searched none is using the Dbus mechanism to install extensions, they just manually unzip archives.... whereas the Dbus interface seems to be more robust, the Firefox/Chrome official extension uses the Dbus interface.
That is why I implemented a command line tool based on Dbus messages, but in case you find it useful in *gnome-extensions-cli* you can use the file based mechanism with `--backend file`. 
One (only?) advantage is that there is no graphical validation (yes no model dialog) before installing extensions.
