### ISSUE TITLE
Install fails with "ModuleNotFoundError: No module named 'gi'"

### ISSUE THREAD

**Issue by iainelder** [essembeh/gnome-extensions-cli#11]
I install using Pipx.

```console
$ pipx install gnome-extensions-cli
  installed package gnome-extensions-cli 0.1.2, installed using Python 3.8.10
  These apps are now globally available
    - gnome-extensions-cli
done! ✨ 🌟 ✨
```

I try to install [Pano](https://extensions.gnome.org/extension/5278/pano/).

```console
$ gnome-extensions-cli install 5278
Traceback (most recent call last):
  File "/home/isme/.local/bin/gnome-extensions-cli", line 5, in <module>
    from gnome_extensions_cli.cli import main
  File "/home/isme/.local/pipx/venvs/gnome-extensions-cli/lib/python3.8/site-packages/gnome_extensions_cli/cli.py", line 6, in <module>
    from gnome_extensions_cli.manager import (
  File "/home/isme/.local/pipx/venvs/gnome-extensions-cli/lib/python3.8/site-packages/gnome_extensions_cli/manager.py", line 17, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'
```

I notice that the installed version of gext is 0.1.2 and the latest version on PyPI is 0.9.4.

How do I install the latest version?

**Comment by essembeh** [comment]
Hi

For the first problem, gext needs a python package "gi" which should be already installed with your distribution (verified with Debian and Ubuntu)
That's why you should installed gext with system packages as documented in the README.md
```shell
$ pipx install gnome-extensions-cli --system-site-packages
``` 


For the second, I've just tested in a docker container debian:latest and I install the latest version as expected
```sh
root@5ed82f7dbff9:/# pipx install gnome-extensions-cli --system-site-packages
  installed package gnome-extensions-cli 0.9.4, installed using Python 3.9.2
  These apps are now globally available
    - gext
    - gnome-extensions-cli
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx
    ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨

```

I would say the you are using python3.8 and the latest version of gext with python3.8 was 0.1.2.
What distribution are you using?

**Comment by iainelder** [comment]
> What distribution are you using?

I believe Python 3.8 ships with Ubuntu 20.04.

```console
$ lsb_release --description
Description:	Ubuntu 20.04.5 LTS
```

Which Python version do you recommend for the latest overall version?

Thanks for pointing out the install instructions. I'll admit, I didn't read it so carefully :-) I just dove in with a standard pipx install.

gext doesn't produce the error message when I used the documented install command.

```console
$ pipx install gnome-extensions-cli --system-site-packages
  installed package gnome-extensions-cli 0.1.2, installed using Python 3.8.10
  These apps are now globally available
    - gnome-extensions-cli
done! ✨ 🌟 ✨
$ gnome-extensions-cli install 5278
Install pano@elhan.io (v18)
$ gnome-extensions-cli list
Installed extensions:
[ ] desktop-icons@csoriano
[X] pano@elhan.io (v18)
[ ] ubuntu-appindicators@ubuntu.com
[ ] ubuntu-dock@ubuntu.com (v68)
```

**Comment by iainelder** [comment]
I'll close this since the main problem is solved. If you could also advise on the recommended Python version I'd be grateful.

**Comment by essembeh** [comment]
Good you were able to install it with pipx :+1: 

Concerning the python version, I set py39 as the minimum version as it is the default Debian:stable python version.
I should have kept python 38 which is not that outdated ... and not EOL.

I created #12 for that.
