### ISSUE TITLE
Support python 3.8

### ISSUE THREAD

**Issue by essembeh** [essembeh/gnome-extensions-cli#12]

**Comment by iainelder** [comment]
[Python 3.8](https://devguide.python.org/versions/) will get security fixes until 2024-10.

[Ubuntu 20.04](https://ubuntu.com/about/release-cycle), which uses Python 3.8 and Gnome 3.36, gets hardware and maintenance updates till mid 2024 and extended security maintenance till 2030.

So it seems worthwhile to support Python 3.8 for at least another 18 months to make life easier for us Ubuntu 20 users :-)

**Comment by essembeh** [comment]
After reading https://docs.python.org/3/whatsnew/3.9.html I think the current code is already py38 compatible.
