### ISSUE TITLE
feat: non-interactive flag/option for install command

### ISSUE THREAD

**Issue by SimonWoodtli** [essembeh/gnome-extensions-cli#13]
Hello I was wondering if you've already implemented or plan to implement a non-interactive mode to install new extensions. 

So with `gext install ...` the prompt asks for confirmation. I saw in your codebase that the update command already has a -y flag to skip that, which is great for scripting 😄

Can you tell me if there are plans to do the same with the install command, which again would be great for using your tool for scripting. Thank you 🙏

Here is the snippet i meant from update.py in your codebase:

```
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "-y",
        "--yes",
        action="store_true",
        help="do not prompt confirmation for update/install",
    )
 ```

**Comment by essembeh** [comment]
Hi

At the end of the README (https://github.com/essembeh/gnome-extensions-cli#filesystem-backend) you can get some details about the two *backends* used to install extensions.

With default backend (dbus) you get the exact same behavior like the official firefox/chome extension visiting the official Gnome extensions website.
The YES/NO confirm dialog is not in the web extension nor in my app, it is directly in your Gnome Shell.
So, it is not possible to skip this confirm dialog if you use the `--dbus` backend.

But if you use `--filesystem` backend, you do not interact directly with Gnome Shell, so you do not have the confirm dialog.
That might be what you are looking for.

But I think I should update the documentation to reflect this better.

**Comment by essembeh** [comment]
No problem with that, you comment means that I could probably write the documentation in a better way ;)
