### ISSUE TITLE
Error in the README.md?

### ISSUE THREAD

**Issue by le-chartreux** [essembeh/gnome-extensions-cli#17]
Hello Sébastien,

I have seen something that looks like a copy-paste error in your README.md, line 23:

- [...]
- gext install to install extensions
- gext ***install*** to update any or all your extensions → isn't it *update* instead?
- [...]

Thank you for your work, it's very cool :+1:

**Comment by essembeh** [comment]
Hi 
Good catch, thanks for that ;)
Fixed in https://github.com/essembeh/gnome-extensions-cli/commit/8ee43c2a32111e391ea71a15056cc0f54c732b79
