### ISSUE TITLE
[Request Feature] Interactless process

### ISSUE THREAD

**Issue by xelser** [essembeh/gnome-extensions-cli#18]
I'm humbly asking for an automated process (no confirmation flag when installing extensions). Like a normal package manager such as `apt`, `dnf`, `pacman` (`--yes`, `--assumeyes`, `--noconfirm` respectively) and so on...

**Comment by essembeh** [comment]
Hello, 

TL;DR; this is not possible, the "Yes/No" confirmation window you get when installing an extension is in Gnome itself, not in `gext`. You have to use `--filesystem` to bypass this confirmation.


This has been discussed in #13 already.
See https://github.com/essembeh/gnome-extensions-cli/issues/13#issuecomment-1529160849 for more details.

**Comment by xelser** [comment]
noted, thanks
