### ISSUE TITLE
pydantic.errors.PydanticImportError: `pydantic:NoneStr` has been removed in V2.

### ISSUE THREAD

**Issue by yochananmarqos** [essembeh/gnome-extensions-cli#20]
Installed via my [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/gnome-extensions-cli/PKGBUILD) on Manjaro GNOME (unstable branch) using `python-pydantic` 2.3.0-1:

```
❯ gext list
Traceback (most recent call last):
  File "/usr/bin/gext", line 5, in <module>
    from gnome_extensions_cli.cli import run
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/cli.py", line 10, in <module>
    from .commands import (
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/commands/disable.py", line 7, in <module>
    from ..icons import Color
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/icons.py", line 11, in <module>
    from .schema import AvailableExtension, InstalledExtension
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/schema.py", line 11, in <module>
    from pydantic import BaseModel, Field, NoneStr  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/_migration.py", line 295, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:NoneStr` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.3/u/import-error
```

**Comment by essembeh** [comment]
Hi

It looks like you have installed `gnome-extensions-cli` with `pydantic` 2.x
If you take a look at the https://github.com/essembeh/gnome-extensions-cli/blob/47b5c80b7660362771c15910b0d81809de48a63c/pyproject.toml#L18 
The `pydantic` requirement is >= 1.10.4 and < 2.0.0, see [Poetry documentation](https://python-poetry.org/docs/dependency-specification/#caret-requirements)

I don't know PKGBUILD, but you may have to configure your build to respect the poetry requirements and not the latest version?

**Comment by yochananmarqos** [comment]
Yes, I realized that this project requires an older version of Pydantic. I was letting you know as any distro that has moved on to 2.XX cannot use this program.

On rolling release distributions like Manjaro (based on Arch), packages are updated to the latest versions. If some package requires a legacy dependency version that cannot be updated to the new version, a legacy dependency mayh be kept around; however only as long as it's required. 

To make this work, one could add a `python-pydantic1` package at say v1.10.12 (last 1.XX version) package to the AUR (Arch User Repository) that this could depend on. I've let the AUR maintainer know. I was just curious and attempted to package it properly.

**Comment by essembeh** [comment]
I know that pydantic 2 has been out for weeks now, there is not too much code to adapt, and I plan to upgrade it asap.

But keeping all the requirements up to date few days after their releases is an endless time consuming task.
That's why I would suggest to try installing python 3rd party  apps like gext using pipx.
It create isolated virtualenv for each app with needed version of requirements.
Maybe you'll find this tool as useful as I do ;)

**Comment by essembeh** [comment]
Could you please test the branch [bump-pydantic](https://github.com/essembeh/gnome-extensions-cli/tree/bump-pydantic) ?

**Comment by yochananmarqos** [comment]
Yes, it works.
