### ISSUE TITLE
Error when trying to disable extension

### ISSUE THREAD

**Issue by igrikus** [essembeh/gnome-extensions-cli#24]
I am trying to disable the `x11gestures@joseexposito.github.io` extension (included by default on Manjaro):

```
gnome-extensions-cli disable "x11gestures@joseexposito.github.io"
```

I am met with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/gnome-extensions-cli", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/cli.py", line 116, in run
    raise error
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/cli.py", line 108, in run
    handler(args, manager, store)
  File "/usr/lib/python3.11/site-packages/gnome_extensions_cli/commands/disable.py", line 36, in run
    if args.fix:
       ^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'fix'
```

**Comment by essembeh** [comment]
Hi

I think you are using an old version, this issue should have been fixed in https://github.com/essembeh/gnome-extensions-cli/commit/b9eb209eaf65da640d2bef2c75e2d4ef6c64c86a

Which version are you using? Could you try to upgrade to the latest version ?

Thanks

**Comment by igrikus** [comment]
Hi @essembeh, thank you for the fast response!

I am using AUR which ironically was last updated on Feb. 7 and commit you mentioned was made on Feb. 8 😁

AFAIU you're not a maintainer of the AUR package, so I have no questions for you. Closing the issue!
