### ISSUE TITLE
Disable updating system-provided extensions

### ISSUE THREAD

**Issue by eliminmax** [essembeh/gnome-extensions-cli#4]
Hello! I have found `gnome-extensions-cli` to be a useful tool to manage my GNOME extensions on Pop!_OS. The issue is that Pop!_OS includes a number of extensions that are provided through the system package manager. Those packages are correctly identified as `/system` packages, but when I run `gext u`, it tries to install upgrades to them. Would it be possible to add a command-line flag to only upgrade user extensions?

**Comment by essembeh** [comment]
Hi

This is a good idea, would a `--user` argument do the work for you?
So that the default behavior would remain to update all extensions, because I also have system extensions in Debian and I want to update them like the official browser extension does.

Any other suggestion?

**Comment by eliminmax** [comment]
A `--user` argument would be perfect! Thanks for getting back to me so fast!
